### ISSUE TITLE
http.MethodNotAllowed() expects arguments always

### ISSUE THREAD

**Issue by limbera** [funkybob/django-nap#67]
Not sure if this is a bug, but if you try to call http.MethodNotAllowed() without any parameters it 500s. Passing an arbitrary parameter fixes it.

Eg this does not 500:
http.MethodNotAllowed({'error':'error'}) 

This does:
http.MethodNotAllowed()

```
Traceback;
[09/Dec/2015 10:11:34] ERROR [django.request:256] Internal Server Error: /api/team/eject/
Traceback (most recent call last):
  File "/Users/dre/Envs/gametraka_project/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/dre/code/gametraka_project/apps/teams/rest_views.py", line 74, in team_eject
    return http.MethodNotAllowed()
TypeError: __init__() takes at least 2 arguments (1 given)
```

**Comment by funkybob** [comment]
First argument to MethodNotAllowed, very much like Django's `django.http.HttpResponseNotAllowed` is a list of methods that are allowed.

e.g.

    return http.MethodNotAllowed(['GET', 'PUT', 'PATCH'])
